//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumirWsSoap.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WsSoapSoap")]
    public interface WsSoapSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ws_listar_artistas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ws_listar_artistas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ws_listar_artistas", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ws_listar_artistasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ws_listar_generos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ws_listar_generos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ws_listar_generos", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ws_listar_generosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ws_listar_albumes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ws_listar_albumes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ws_listar_albumes", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ws_listar_albumesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ws_insertar_artista", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ws_insertar_artista(string nombreArtista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ws_insertar_artista", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ws_insertar_artistaAsync(string nombreArtista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ws_insertar_genero", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ws_insertar_genero(string nombreGenero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ws_insertar_genero", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ws_insertar_generoAsync(string nombreGenero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ws_insertar_album", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ws_insertar_album(string tituloAlbum, int idArtista, int idGenero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ws_insertar_album", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ws_insertar_albumAsync(string tituloAlbum, int idArtista, int idGenero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ws_editar_artista", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ws_editar_artista(int idArtista, string nombreArtista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ws_editar_artista", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ws_editar_artistaAsync(int idArtista, string nombreArtista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ws_editar_genero", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ws_editar_genero(int idGenero, string nombreGenero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ws_editar_genero", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ws_editar_generoAsync(int idGenero, string nombreGenero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ws_editar_album", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ws_editar_album(int idAlbum, string tituloAlbum, int idArtista, int idGenero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ws_editar_album", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ws_editar_albumAsync(int idAlbum, string tituloAlbum, int idArtista, int idGenero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ws_eliminar_artista", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ws_eliminar_artista(int idArtista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ws_eliminar_artista", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ws_eliminar_artistaAsync(int idArtista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ws_eliminar_genero", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ws_eliminar_genero(int idGenero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ws_eliminar_genero", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ws_eliminar_generoAsync(int idGenero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ws_eliminar_album", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ws_eliminar_album(int idAlbum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ws_eliminar_album", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ws_eliminar_albumAsync(int idAlbum);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsSoapSoapChannel : ConsumirWsSoap.ServiceReference1.WsSoapSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsSoapSoapClient : System.ServiceModel.ClientBase<ConsumirWsSoap.ServiceReference1.WsSoapSoap>, ConsumirWsSoap.ServiceReference1.WsSoapSoap {
        
        public WsSoapSoapClient() {
        }
        
        public WsSoapSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsSoapSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsSoapSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsSoapSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ws_listar_artistas() {
            return base.Channel.ws_listar_artistas();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ws_listar_artistasAsync() {
            return base.Channel.ws_listar_artistasAsync();
        }
        
        public System.Data.DataSet ws_listar_generos() {
            return base.Channel.ws_listar_generos();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ws_listar_generosAsync() {
            return base.Channel.ws_listar_generosAsync();
        }
        
        public System.Data.DataSet ws_listar_albumes() {
            return base.Channel.ws_listar_albumes();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ws_listar_albumesAsync() {
            return base.Channel.ws_listar_albumesAsync();
        }
        
        public string ws_insertar_artista(string nombreArtista) {
            return base.Channel.ws_insertar_artista(nombreArtista);
        }
        
        public System.Threading.Tasks.Task<string> ws_insertar_artistaAsync(string nombreArtista) {
            return base.Channel.ws_insertar_artistaAsync(nombreArtista);
        }
        
        public string ws_insertar_genero(string nombreGenero) {
            return base.Channel.ws_insertar_genero(nombreGenero);
        }
        
        public System.Threading.Tasks.Task<string> ws_insertar_generoAsync(string nombreGenero) {
            return base.Channel.ws_insertar_generoAsync(nombreGenero);
        }
        
        public string ws_insertar_album(string tituloAlbum, int idArtista, int idGenero) {
            return base.Channel.ws_insertar_album(tituloAlbum, idArtista, idGenero);
        }
        
        public System.Threading.Tasks.Task<string> ws_insertar_albumAsync(string tituloAlbum, int idArtista, int idGenero) {
            return base.Channel.ws_insertar_albumAsync(tituloAlbum, idArtista, idGenero);
        }
        
        public string ws_editar_artista(int idArtista, string nombreArtista) {
            return base.Channel.ws_editar_artista(idArtista, nombreArtista);
        }
        
        public System.Threading.Tasks.Task<string> ws_editar_artistaAsync(int idArtista, string nombreArtista) {
            return base.Channel.ws_editar_artistaAsync(idArtista, nombreArtista);
        }
        
        public string ws_editar_genero(int idGenero, string nombreGenero) {
            return base.Channel.ws_editar_genero(idGenero, nombreGenero);
        }
        
        public System.Threading.Tasks.Task<string> ws_editar_generoAsync(int idGenero, string nombreGenero) {
            return base.Channel.ws_editar_generoAsync(idGenero, nombreGenero);
        }
        
        public string ws_editar_album(int idAlbum, string tituloAlbum, int idArtista, int idGenero) {
            return base.Channel.ws_editar_album(idAlbum, tituloAlbum, idArtista, idGenero);
        }
        
        public System.Threading.Tasks.Task<string> ws_editar_albumAsync(int idAlbum, string tituloAlbum, int idArtista, int idGenero) {
            return base.Channel.ws_editar_albumAsync(idAlbum, tituloAlbum, idArtista, idGenero);
        }
        
        public string ws_eliminar_artista(int idArtista) {
            return base.Channel.ws_eliminar_artista(idArtista);
        }
        
        public System.Threading.Tasks.Task<string> ws_eliminar_artistaAsync(int idArtista) {
            return base.Channel.ws_eliminar_artistaAsync(idArtista);
        }
        
        public string ws_eliminar_genero(int idGenero) {
            return base.Channel.ws_eliminar_genero(idGenero);
        }
        
        public System.Threading.Tasks.Task<string> ws_eliminar_generoAsync(int idGenero) {
            return base.Channel.ws_eliminar_generoAsync(idGenero);
        }
        
        public string ws_eliminar_album(int idAlbum) {
            return base.Channel.ws_eliminar_album(idAlbum);
        }
        
        public System.Threading.Tasks.Task<string> ws_eliminar_albumAsync(int idAlbum) {
            return base.Channel.ws_eliminar_albumAsync(idAlbum);
        }
    }
}
